services:
  postgres:
    image: postgres:16
    container_name: servidor_postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: brecha_digital
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data: